### ISSUE TITLE
Application keeps posting in the Changelog channel about 3 times a month

### ISSUE THREAD

**Issue by DanceParty** [NYTDiscordBot/DiscordBot#8]

**Comment by DanceParty** [comment]
Finally happened again with this log:

```
/home/jkdance123/.pm2/logs/nyt-crossword-bot-error.log last 15 lines:
0|nyt-cros | /home/jkdance123/apps/nyt-crossword-discord-bot/node_modules/discord.js/src/client/actions/MessageCreate.js:11
0|nyt-cros |       const existing = channel.messages.cache.get(data.id);
0|nyt-cros |                                         ^
0|nyt-cros |
0|nyt-cros | TypeError: Cannot read property 'cache' of undefined
0|nyt-cros |     at MessageCreateAction.handle (/home/jkdance123/apps/nyt-crossword-discord-bot/node_modules/discord.js/src/client/actions/MessageCreate.js:11:41)
0|nyt-cros |     at Object.module.exports [as MESSAGE_CREATE] (/home/jkdance123/apps/nyt-crossword-discord-bot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
0|nyt-cros |     at WebSocketManager.handlePacket (/home/jkdance123/apps/nyt-crossword-discord-bot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
0|nyt-cros |     at WebSocketShard.onPacket (/home/jkdance123/apps/nyt-crossword-discord-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
0|nyt-cros |     at WebSocketShard.onMessage (/home/jkdance123/apps/nyt-crossword-discord-bot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
0|nyt-cros |     at WebSocket.onMessage (/home/jkdance123/apps/nyt-crossword-discord-bot/node_modules/ws/lib/event-target.js:132:16)
0|nyt-cros |     at WebSocket.emit (node:events:394:28)
0|nyt-cros |     at Receiver.receiverOnMessage (/home/jkdance123/apps/nyt-crossword-discord-bot/node_modules/ws/lib/websocket.js:825:20)
0|nyt-cros |     at Receiver.emit (node:events:394:28)
0|nyt-cros |     at Receiver.dataMessage (/home/jkdance123/apps/nyt-crossword-discord-bot/node_modules/ws/lib/receiver.js:437:14)
```

which looks like it is failing within the discord.js package.
